### PR TITLE
Updated Dio to ^4.0.0

### PR DESCRIPTION
**Pull request by Jethro87**
Bumped Dio to fix dependency issues with regards to null safety. More info in #39. Thanks!

### CODE REVIEW

**Comment by curquiza** [comment]
Hello @Jethro87, thanks for your PR :)
I think there is a missing step in this PR because all the CIs fail with this error:
```
Because no versions of dio match >4.0.0 <5.0.0 and dio 4.0.0 requires SDK version >=2.12.0 <3.0.0, dio ^4.0.0 is forbidden.
So, because meilisearch depends on dio ^4.0.0, version solving failed.
```
https://github.com/meilisearch/meilisearch-dart/pull/41/checks?check_run_id=2467702212

**Comment by Jethro87** [comment]
@curquiza I believe this issue can be solved in a couple of different ways. One, remove testing of dark SDK's <2.12.0 in `pre-release-tests` and `tests`. Or, migrate to full null-safety, and don't change the testing of dark SDK's <2.12.0.

I don't thave the capacity to migrate meilisearch to null-safety myself, but it is becoming increasingly important as I don't think users will be able to use this package if it remains non-null-safe and/or depends on Dio <4.0.0.

So, not quite sure what to do here.

**Comment by curquiza** [comment]
Maybe your PR might wait for this issue to be solved #37? Is it what you mean?
@TheMisir assigned himself on this issue so he will do it when he's available 🙂

**Comment by Jethro87** [comment]
@curquiza Yes, I think migrating to null-safety as soon as possible is the best way forward. Thanks.

**Comment by TheMisir** [comment]
I'm closing this one since it's already solved with nnbd migration - #42 .

**Pull request closed without merging**
