### PR TITLE
Remove useless message from README.md

### PR DESCRIPTION
**Pull request by brunoocasali**

### CODE REVIEW

**Review by ahmednfwela — APPROVED** [review]
No missing features on my watch!

**Comment by brunoocasali** [comment]
You rock @ahmednfwela 👨‍🎤 🤘

**Comment by brunoocasali** [comment]
bors merge

**Comment by ahmednfwela** [comment]
merge this first to fix CI fail https://github.com/meilisearch/meilisearch-dart/pull/313

**Comment by brunoocasali** [comment]
bors merge

**Comment by brunoocasali** [comment]
btw: there is no need to update the branch @ahmednfwela bors take care of that for us! Unless we have some conflicts 😬

**Pull request merged**
