### PR TITLE
Raise min Dart SDK to 3.0.0

### PR DESCRIPTION
**Pull request by ahmednfwela**
# Pull Request

## What does this PR do?
- Raise the minimum dart sdk to 3.0.0, this lets us use the [super parameters](https://dart.dev/language/constructors#super-parameters) feature, class modifiers, records and patterns

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by brunoocasali** [comment]
I think we can go for the v3 directly after v1.2 :)

**Comment by ahmednfwela** [comment]
great! Should I base all coming v1.2 PRs on this PR then?

**Comment by brunoocasali** [comment]
Hi @ahmednfwela you can update your PR to make it points to v3 of Dart, then we can release it alone, and you can base the v1.2 PRs in the bump as usual (I will rebase the bump with main).

**Comment by ahmednfwela** [comment]
@brunoocasali I updated the PR to raise the min sdk version to v3.0.0
I also changed the example to depend on meilisearch from path instead of pub.dev
and updated contributing.md accordingly

**Review by brunoocasali — APPROVED** [review]
bors merge and viva Dart 3!

**Comment by brunoocasali** [comment]
bors merge

**Pull request merged**
