### PR TITLE
Error handler

### PR DESCRIPTION
**Pull request by curquiza**
Add `MeiliSearchApiException` and `ConnectionException`

### CODE REVIEW

**Comment by curquiza** [comment]
If you have time @TheMisir to review this error handler, this would be really awesome 😁

**Comment by curquiza** [comment]
Hello @TheMisir!
Thanks for both of your feedback, I will take them into account and I will update this PR as soon as possible 🙂

**Review by TheMisir — APPROVED** [review]
LGTM

**Comment by curquiza** [comment]
Hello @TheMisir!
I tried to use interceptors, but it was not a success.

As a test, I tried to use interception in the `getMethod` method first:
```dart
@override
  Future<Response<T>> getMethod<T>(String path,
      {Map<String, dynamic> queryParameters}) async {
    var response;
    dio.interceptors.add(InterceptorsWrapper(
      onError: (DioError e) {
        if (e.type == DioErrorType.RESPONSE) {
          return MeiliSearchApiException(e.message, e.response.data);
        } else if (e.type == DioErrorType.DEFAULT) {
          return CommunicationException(e.message);
        }
        return e;
      },
    ));
    response = await dio.get<T>(
      path,
      queryParameters: queryParameters,
    );
    return await response;
  }
```
(I also tried to replace `return` by `throw` but this is the same result)
And here is the `main.dart`
```dart
import 'package:meilisearch/meilisearch.dart';

void main() async {
  var client = MeiliSearchClient('http://127.0.0.1:7700', 'masterKey');
  var index = await client.getIndex('boo');
}
```
But a `DioError [DioErrorType.DEFAULT]` is returned and not a `MeiliSearchApiException`. I indeed want the users to be able to catch the `MeiliSearchApiException` so that they can use the variable of the custom exception this way:
```dart
try {
  var index = await client.getIndex('boo');
} catch (e) {
  print(e.errorCode);
}
```

I'm a dart beginner, do I miss something?

**Comment by TheMisir** [comment]
Oh that's true. Dio will throw DioError from interceptors. Also your implementation does isolates http client from the library itself which gives us opportunity to use different http client in future without changing much code.

**Comment by curquiza** [comment]
Ok, so we can let my code as it is now on your opinion?

**Comment by TheMisir** [comment]
Yes

**Comment by curquiza** [comment]
Great! 
Thanks for your reactivity and make me discover the interceptors 😁

bors merge

**Pull request merged**
